version: '3.7'

services:
  reverse-proxy:
    ports:
      - '8080:80'
    volumes:
      - './services/reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf'
  app:
    build:
      target: 'build'
    command: './bin/start-dev.sh'
    volumes:
      - './services/app:/app'

  api:
    build:
      target: 'build'
    command: './bin/start-dev.sh'
    volumes:
      - './services/api:/app'
      - 'ts-cache-api:/app-cache/ts-cache'
    # ports:
    #   - '9229:9229'

  db:
    # ports:
    #   - '54320:5432'

volumes:
  ts-cache-api:
