version: '3.7'

services:
  reverse-proxy:
    build:
      context: ./services/reverse-proxy
    depends_on:
      - app
      - api
    restart: always

  app:
    build:
      context: ./services/app
      target: prod
    restart: always

  api:
    build:
      context: ./services/api
      target: prod
    restart: always
    env_file:
      - ENV
    depends_on:
      - db

  db:
    image: postgres:11.4
    restart: always
    env_file:
      - ENV
    volumes:
      - data_db:/var/lib/postgresql/data

volumes:
  data_db:
