version: '3.7'

services:
  reverse-proxy:
    ports:
      - '8080:80'
    volumes:
      - './services/reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf'
  app:
    build:
      target: 'build'
    command: './bin/start-dev.sh'
    volumes:
      - './services/app/src:/app/src'

  api:
    build:
      target: 'build'
    command: './bin/start-dev.sh'
    volumes:
      - './services/api/src:/app/src'
      - 'ts-cache-api:/app-cache/ts-cache'
    ports:
      # debug port
      - '9229:9229'

  db:
    ports:
      # Postgres db port
      - '54320:5432'

volumes:
  ts-cache-api:
