# Base
FROM node:14.18.0-alpine AS base
WORKDIR /app
COPY ./package*.json ./

# Build
FROM base AS build
RUN npm ci
COPY ./tsconfig.json ./tsconfig.json
COPY ./webpack.config.js ./webpack.config.js
COPY ./bin ./bin
COPY ./src ./src
RUN npx webpack --mode production

# Production
FROM nginx:stable-alpine as prod
COPY --from=build /app/dist /app/dist
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

