# Base
FROM node:14.18.0-alpine as base
WORKDIR /app
COPY ./package*.json ./

# Build
FROM base as build
RUN npm ci
COPY ./tsconfig.json ./tsconfig.json
COPY ./src ./src
COPY ./bin ./bin
RUN npx tsc

# Production
FROM base as prod
RUN npm ci --only=production
COPY ./bin ./bin
COPY --from=build /app/dist /app/dist

CMD ./bin/start-prod.sh
